import mongoose from 'mongoose';
/*
/*
* Script for seeding db with large dataset -
* 1000+ risks and 20 categories
* */

import 'dotenv/config';
import { Risk } from '../models/risk.js';
import { Category } from '../models/category.js';
import connectDB from '../db.js';

function randomString(length: number): string {
	const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
	let result = '';
	for (let i = 0; i < length; i += 1) {
		result += chars.charAt(Math.floor(Math.random() * chars.length));
	}
	return result;
}

function generateRandomRisks(
	count: number,
	categories: Array<{ _id: mongoose.Types.ObjectId }>
): Array<{ name: string; description: string; categoryId: mongoose.Types.ObjectId; createdBy: string; resolved: boolean }> {
	const categoryIds = categories.map((cat) => cat._id);
	return Array.from({ length: count }, (_, idx) => {
		const categoryId = categoryIds[Math.floor(Math.random() * categoryIds.length)];
		return {
			name: `Auto Risk ${idx + 1} ${randomString(6)}`,
			description: `Generated risk description ${randomString(24)}`,
			categoryId,
			createdBy: `auto-${randomString(8)}`,
			resolved: Math.random() > 0.5,
		};
	});
}

const categoriesData = [
	{
		name: 'Security',
		description: 'Security-related risks including vulnerabilities, breaches, and access control issues',
		createdBy: 'security-team',
	},
	{
		name: 'Operational',
		description: 'Operational risks including system failures, process inefficiencies, and resource constraints',
		createdBy: 'operations-team',
	},
	{
		name: 'Financial',
		description: 'Financial risks including budget overruns, cost management, and revenue impacts',
		createdBy: 'finance-team',
	},
	{
		name: 'Compliance',
		description: 'Compliance risks including regulatory violations, audit failures, and legal requirements',
		createdBy: 'compliance-officer',
	},
	{
		name: 'Technology',
		description: 'Technology risks including infrastructure failures, technical debt, and integration issues',
		createdBy: 'cto',
	},
	{
		name: 'Human Resources',
		description: 'HR risks including talent retention, skill gaps, and organizational changes',
		createdBy: 'hr-director',
	},
	{
		name: 'Legal',
		description: 'Legal risks including contract disputes, intellectual property issues, and litigation',
		createdBy: 'legal-counsel',
	},
	{
		name: 'Environmental',
		description: 'Environmental risks including sustainability concerns, resource consumption, and climate impact',
		createdBy: 'sustainability-manager',
	},
	{
		name: 'Strategic',
		description: 'Strategic risks including market changes, competitive threats, and business model disruptions',
		createdBy: 'ceo',
	},
	{
		name: 'Reputational',
		description: 'Reputational risks including brand damage, public relations issues, and customer trust',
		createdBy: 'pr-manager',
	},
	{
		name: 'Architecture',
		description: 'System architecture risks including scalability, maintainability, and design decisions',
		createdBy: 'cto',
	},
	{
		name: 'Innovation',
		description: 'Innovation risks including R&D investments, technology adoption, and competitive differentiation',
		createdBy: 'cto',
	},
	{
		name: 'Data Management',
		description: 'Data management risks including data quality, governance, and lifecycle management',
		createdBy: 'cto',
	},
	{
		name: 'Platform',
		description: 'Platform risks including infrastructure reliability, vendor management, and service delivery',
		createdBy: 'cto',
	},
	{
		name: 'Digital Transformation',
		description: 'Digital transformation risks including change management, technology integration, and process modernization',
		createdBy: 'cto',
	},
	{
		name: 'Quality Assurance',
		description: 'Quality assurance risks including testing gaps, defect management, and quality control processes',
		createdBy: 'qa-manager',
	},
	{
		name: 'Vendor Management',
		description: 'Vendor management risks including supplier dependencies, contract management, and vendor performance',
		createdBy: 'procurement-director',
	},
	{
		name: 'Business Continuity',
		description: 'Business continuity risks including disaster recovery, crisis management, and operational resilience',
		createdBy: 'operations-manager',
	},
	{
		name: 'Customer Experience',
		description: 'Customer experience risks including service quality, customer satisfaction, and user engagement',
		createdBy: 'customer-success-manager',
	},
	{
		name: 'Supply Chain',
		description: 'Supply chain risks including logistics, inventory management, and supplier relationships',
		createdBy: 'supply-chain-manager',
	},
];

const risksData = [
	{
		name: 'SQL Injection Vulnerability',
		description: 'Database queries are vulnerable to SQL injection attacks due to improper input sanitization',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Weak Password Policy',
		description: 'Current password policy allows weak passwords, increasing risk of unauthorized access',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Missing SSL/TLS Certificate',
		description: 'API endpoints are not using SSL/TLS encryption, exposing data in transit',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: true,
	},
	{
		name: 'Unauthorized API Access',
		description: 'API endpoints lack proper authentication mechanisms, allowing unauthorized access',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Cross-Site Scripting (XSS)',
		description: 'User input is not properly sanitized, allowing potential XSS attacks in web interface',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Outdated Dependencies',
		description: 'Multiple npm packages contain known security vulnerabilities and need updates',
		categoryName: 'Security',
		createdBy: 'security-scanner',
		resolved: false,
	},
	{
		name: 'Exposed API Keys',
		description: 'API keys found in public repository, requiring immediate rotation and removal',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: true,
	},
	{
		name: 'Insufficient Logging',
		description: 'Security events are not properly logged, making incident detection difficult',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Missing Rate Limiting',
		description: 'API endpoints lack rate limiting, vulnerable to brute force and DDoS attacks',
		categoryName: 'Security',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Insecure Data Storage',
		description: 'Sensitive user data stored in plaintext instead of encrypted format',
		categoryName: 'Security',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Database Performance Degradation',
		description: 'Query response times have increased by 300% over the past month, affecting user experience',
		categoryName: 'Operational',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Single Point of Failure',
		description: 'Application relies on single database server without redundancy or failover mechanism',
		categoryName: 'Operational',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Insufficient Backup Strategy',
		description: 'Current backup frequency is weekly, which may result in significant data loss in case of failure',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'High Server Load',
		description: 'CPU usage consistently above 85% during peak hours, risking service degradation',
		categoryName: 'Operational',
		createdBy: 'monitoring-system',
		resolved: false,
	},
	{
		name: 'Memory Leak in Production',
		description: 'Application memory usage gradually increases over time, requiring periodic restarts',
		categoryName: 'Operational',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Missing Error Handling',
		description: 'Several API endpoints lack proper error handling, causing unhandled exceptions',
		categoryName: 'Operational',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Monitoring',
		description: 'No comprehensive monitoring system in place, making issue detection reactive rather than proactive',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Outdated Documentation',
		description: 'API documentation is outdated and does not reflect current implementation, causing integration issues',
		categoryName: 'Operational',
		createdBy: 'technical-writer',
		resolved: true,
	},
	{
		name: 'Resource Exhaustion Risk',
		description: 'Disk space usage growing at 10GB per week, may reach capacity within 2 months',
		categoryName: 'Operational',
		createdBy: 'system-admin',
		resolved: false,
	},
	{
		name: 'Third-Party Service Dependency',
		description: 'Critical functionality depends on external service with 99% uptime SLA, creating reliability risk',
		categoryName: 'Operational',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Privilege Escalation Vulnerability',
		description: 'Users can escalate privileges through application logic flaw',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Session Hijacking Risk',
		description: 'Session tokens not properly secured, vulnerable to hijacking attacks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Insecure Direct Object Reference',
		description: 'Application exposes internal object references without proper authorization checks',
		categoryName: 'Security',
		createdBy: 'security-scanner',
		resolved: false,
	},
	{
		name: 'CSRF Protection Missing',
		description: 'Forms lack CSRF tokens, vulnerable to cross-site request forgery',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: true,
	},
	{
		name: 'Insecure File Upload',
		description: 'File upload functionality allows malicious file execution',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Broken Authentication',
		description: 'Authentication mechanism has flaws allowing bypass or brute force attacks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Sensitive Data Exposure',
		description: 'Application logs contain sensitive information in plaintext',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'XML External Entity Injection',
		description: 'XML processors vulnerable to XXE attacks, allowing file system access',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Insecure Deserialization',
		description: 'Deserialization of untrusted data can lead to remote code execution',
		categoryName: 'Security',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Using Components with Known Vulnerabilities',
		description: 'Third-party libraries contain unpatched security vulnerabilities',
		categoryName: 'Security',
		createdBy: 'security-scanner',
		resolved: false,
	},
	{
		name: 'Insufficient Security Logging',
		description: 'Security events not logged with sufficient detail for forensic analysis',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Weak Encryption Algorithms',
		description: 'Application uses deprecated encryption algorithms vulnerable to attacks',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: true,
	},
	{
		name: 'Missing Security Headers',
		description: 'HTTP security headers not configured, increasing attack surface',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'Insecure API Design',
		description: 'API endpoints expose sensitive operations without proper authentication',
		categoryName: 'Security',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Hardcoded Credentials',
		description: 'Application code contains hardcoded passwords and API keys',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Insufficient Input Validation',
		description: 'User inputs not properly validated, allowing malicious payloads',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Missing Multi-Factor Authentication',
		description: 'Critical accounts lack MFA, increasing risk of unauthorized access',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Insecure Cookie Configuration',
		description: 'Cookies not marked as secure or HttpOnly, vulnerable to theft',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: true,
	},
	{
		name: 'Insufficient Access Controls',
		description: 'Role-based access controls not properly implemented across all endpoints',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Vulnerable Third-Party Integrations',
		description: 'Third-party services integrated without proper security assessment',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Network Latency Issues',
		description: 'High network latency affecting application performance in certain regions',
		categoryName: 'Operational',
		createdBy: 'network-engineer',
		resolved: false,
	},
	{
		name: 'Insufficient Load Testing',
		description: 'Application not tested under production load conditions',
		categoryName: 'Operational',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Database Connection Pool Exhaustion',
		description: 'Database connection pool frequently exhausted, causing request failures',
		categoryName: 'Operational',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Missing Disaster Recovery Plan',
		description: 'No documented disaster recovery procedures in place',
		categoryName: 'Operational',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Capacity Planning',
		description: 'No capacity planning process, risking resource shortages during growth',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Degradation During Peak Hours',
		description: 'Application performance degrades significantly during peak usage periods',
		categoryName: 'Operational',
		createdBy: 'monitoring-system',
		resolved: false,
	},
	{
		name: 'Incomplete Deployment Procedures',
		description: 'Deployment process lacks proper rollback mechanisms and testing',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'Missing Health Check Endpoints',
		description: 'No health check endpoints for monitoring application status',
		categoryName: 'Operational',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Inefficient Database Queries',
		description: 'Multiple queries lack proper indexing, causing slow response times',
		categoryName: 'Operational',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Insufficient Logging Infrastructure',
		description: 'Logging system cannot handle peak load, causing log loss',
		categoryName: 'Operational',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'Missing Automated Testing',
		description: 'Critical functionality lacks automated tests, increasing regression risk',
		categoryName: 'Operational',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Alerting System',
		description: 'Alerting system generates too many false positives, reducing effectiveness',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Version Control Issues',
		description: 'Code repository lacks proper branching strategy and code review process',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: false,
	},
	{
		name: 'Insufficient Scalability',
		description: 'Application architecture cannot scale horizontally to meet demand',
		categoryName: 'Operational',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Missing Performance Benchmarks',
		description: 'No performance benchmarks established, making optimization difficult',
		categoryName: 'Operational',
		createdBy: 'performance-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Change Management',
		description: 'No formal change management process, increasing deployment risks',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Dependency Chain Risk',
		description: 'Critical service depends on multiple other services, creating cascade failure risk',
		categoryName: 'Operational',
		createdBy: 'system-architect',
		resolved: false,
	},
	{
		name: 'Missing Configuration Management',
		description: 'Application configurations not properly versioned or managed',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'Insufficient Incident Response',
		description: 'No documented incident response procedures for production issues',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Legacy System Integration Issues',
		description: 'Integration with legacy systems causing performance and reliability problems',
		categoryName: 'Operational',
		createdBy: 'integration-engineer',
		resolved: false,
	},
	{
		name: 'Budget Overrun Risk',
		description: 'Project costs exceeding allocated budget by 15%',
		categoryName: 'Financial',
		createdBy: 'project-manager',
		resolved: false,
	},
	{
		name: 'Unexpected Infrastructure Costs',
		description: 'Cloud infrastructure costs 40% higher than projected',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Currency Exchange Rate Volatility',
		description: 'International operations exposed to currency fluctuation risks',
		categoryName: 'Financial',
		createdBy: 'finance-director',
		resolved: false,
	},
	{
		name: 'Payment Processing Fees',
		description: 'High payment processing fees reducing profit margins',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Delayed Revenue Recognition',
		description: 'Revenue recognition delays affecting cash flow projections',
		categoryName: 'Financial',
		createdBy: 'accounting-manager',
		resolved: false,
	},
	{
		name: 'Insufficient Financial Reserves',
		description: 'Company lacks adequate financial reserves for unexpected expenses',
		categoryName: 'Financial',
		createdBy: 'cfo',
		resolved: false,
	},
	{
		name: 'Tax Compliance Issues',
		description: 'Potential tax compliance issues in new markets',
		categoryName: 'Financial',
		createdBy: 'tax-advisor',
		resolved: false,
	},
	{
		name: 'Vendor Payment Delays',
		description: 'Delays in vendor payments affecting supplier relationships',
		categoryName: 'Financial',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Investment Portfolio Risk',
		description: 'Company investments exposed to market volatility',
		categoryName: 'Financial',
		createdBy: 'finance-director',
		resolved: false,
	},
	{
		name: 'Credit Risk Exposure',
		description: 'High exposure to customer credit defaults',
		categoryName: 'Financial',
		createdBy: 'credit-manager',
		resolved: false,
	},
	{
		name: 'Inflation Impact on Costs',
		description: 'Rising inflation increasing operational costs faster than revenue',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Fraud Detection Gaps',
		description: 'Insufficient fraud detection mechanisms in payment systems',
		categoryName: 'Financial',
		createdBy: 'security-team',
		resolved: true,
	},
	{
		name: 'Subscription Revenue Churn',
		description: 'High customer churn rate affecting recurring revenue',
		categoryName: 'Financial',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Regulatory Fine Risk',
		description: 'Potential regulatory fines for non-compliance',
		categoryName: 'Financial',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Insurance Coverage Gaps',
		description: 'Insufficient insurance coverage for key business risks',
		categoryName: 'Financial',
		createdBy: 'risk-manager',
		resolved: false,
	},
	{
		name: 'Cost Overrun in Development',
		description: 'Software development costs exceeding estimates',
		categoryName: 'Financial',
		createdBy: 'project-manager',
		resolved: false,
	},
	{
		name: 'Market Downturn Impact',
		description: 'Economic downturn affecting customer spending',
		categoryName: 'Financial',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Inadequate Pricing Strategy',
		description: 'Current pricing model not covering full cost structure',
		categoryName: 'Financial',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Foreign Exchange Losses',
		description: 'Unhedged foreign currency exposure causing losses',
		categoryName: 'Financial',
		createdBy: 'finance-director',
		resolved: false,
	},
	{
		name: 'Insufficient Working Capital',
		description: 'Working capital constraints limiting growth opportunities',
		categoryName: 'Financial',
		createdBy: 'cfo',
		resolved: false,
	},
	{
		name: 'Revenue Recognition Compliance',
		description: 'Complex revenue recognition requirements causing accounting challenges',
		categoryName: 'Financial',
		createdBy: 'accounting-manager',
		resolved: true,
	},
	{
		name: 'Customer Payment Terms Risk',
		description: 'Extended payment terms increasing cash flow risk',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Technology Investment ROI',
		description: 'Technology investments not delivering expected returns',
		categoryName: 'Financial',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Competitive Pricing Pressure',
		description: 'Competitors forcing price reductions, impacting margins',
		categoryName: 'Financial',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Inadequate Financial Controls',
		description: 'Weak internal financial controls increasing fraud risk',
		categoryName: 'Financial',
		createdBy: 'internal-auditor',
		resolved: false,
	},
	{
		name: 'GDPR Compliance Gaps',
		description: 'Data processing activities not fully compliant with GDPR requirements',
		categoryName: 'Compliance',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'HIPAA Violation Risk',
		description: 'Healthcare data handling may violate HIPAA regulations',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'PCI DSS Non-Compliance',
		description: 'Payment card data processing not meeting PCI DSS standards',
		categoryName: 'Compliance',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'SOX Compliance Issues',
		description: 'Financial reporting controls not meeting SOX requirements',
		categoryName: 'Compliance',
		createdBy: 'internal-auditor',
		resolved: false,
	},
	{
		name: 'Missing Privacy Policy Updates',
		description: 'Privacy policy not updated to reflect current data practices',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Insufficient Audit Trail',
		description: 'System lacks comprehensive audit trail for compliance requirements',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Data Retention Policy Violations',
		description: 'Data retention practices not aligned with regulatory requirements',
		categoryName: 'Compliance',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Export Control Compliance',
		description: 'Software exports may violate international trade regulations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Accessibility Compliance Gaps',
		description: 'Application not meeting WCAG accessibility standards',
		categoryName: 'Compliance',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Industry-Specific Regulations',
		description: 'New industry regulations requiring system modifications',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Third-Party Compliance Risk',
		description: 'Vendors not meeting required compliance standards',
		categoryName: 'Compliance',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Data Breach Notification Requirements',
		description: 'Insufficient procedures for timely data breach notifications',
		categoryName: 'Compliance',
		createdBy: 'security-team',
		resolved: true,
	},
	{
		name: 'Cross-Border Data Transfer Issues',
		description: 'Data transfers to certain countries may violate regulations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Employee Data Protection',
		description: 'Employee data handling not compliant with labor regulations',
		categoryName: 'Compliance',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Financial Services Regulations',
		description: 'Operations may require financial services licensing',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Environmental Regulations',
		description: 'Operations not compliant with environmental regulations',
		categoryName: 'Compliance',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Consumer Protection Laws',
		description: 'Product features may violate consumer protection regulations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Anti-Money Laundering Requirements',
		description: 'Payment processing may require AML compliance measures',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Licensing and Permits',
		description: 'Missing required business licenses and permits',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Record Keeping Requirements',
		description: 'Insufficient record keeping for regulatory compliance',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Regulatory Change Management',
		description: 'No process for tracking and implementing regulatory changes',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: true,
	},
	{
		name: 'Contract Compliance Issues',
		description: 'Service level agreements not meeting contractual obligations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Intellectual Property Compliance',
		description: 'Potential IP infringement in product features',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Data Localization Requirements',
		description: 'Certain jurisdictions require data to be stored locally',
		categoryName: 'Compliance',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Regulatory Reporting Delays',
		description: 'Delays in submitting required regulatory reports',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Legacy System Dependencies',
		description: 'Critical functionality depends on outdated legacy systems',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Technical Debt Accumulation',
		description: 'Significant technical debt slowing down development velocity',
		categoryName: 'Technology',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'Cloud Provider Lock-in',
		description: 'Heavy dependency on single cloud provider limiting flexibility',
		categoryName: 'Technology',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'API Versioning Issues',
		description: 'Lack of proper API versioning causing breaking changes',
		categoryName: 'Technology',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Microservices Complexity',
		description: 'Microservices architecture becoming too complex to manage',
		categoryName: 'Technology',
		createdBy: 'system-architect',
		resolved: false,
	},
	{
		name: 'Data Migration Challenges',
		description: 'Complex data migration required with high risk of data loss',
		categoryName: 'Technology',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Incompatible Technology Stack',
		description: 'Current technology stack limiting scalability and performance',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Third-Party API Reliability',
		description: 'Critical third-party APIs experiencing frequent outages',
		categoryName: 'Technology',
		createdBy: 'integration-engineer',
		resolved: false,
	},
	{
		name: 'Mobile Platform Fragmentation',
		description: 'Supporting multiple mobile platforms increasing development complexity',
		categoryName: 'Technology',
		createdBy: 'mobile-developer',
		resolved: false,
	},
	{
		name: 'Browser Compatibility Issues',
		description: 'Application not working properly on older browser versions',
		categoryName: 'Technology',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Database Migration Risk',
		description: 'Planned database migration has high risk of downtime',
		categoryName: 'Technology',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Container Orchestration Complexity',
		description: 'Kubernetes setup becoming too complex to maintain',
		categoryName: 'Technology',
		createdBy: 'devops-engineer',
		resolved: true,
	},
	{
		name: 'CI/CD Pipeline Failures',
		description: 'Continuous integration pipeline frequently failing, blocking deployments',
		categoryName: 'Technology',
		createdBy: 'devops-team',
		resolved: false,
	},
	{
		name: 'Code Quality Degradation',
		description: 'Code quality metrics declining over time',
		categoryName: 'Technology',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'Infrastructure Scaling Limitations',
		description: 'Current infrastructure cannot scale to meet demand',
		categoryName: 'Technology',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Technology Vendor Dependency',
		description: 'Heavy reliance on single technology vendor',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Data Synchronization Issues',
		description: 'Data synchronization between systems causing inconsistencies',
		categoryName: 'Technology',
		createdBy: 'integration-engineer',
		resolved: false,
	},
	{
		name: 'Performance Bottlenecks',
		description: 'Multiple performance bottlenecks identified in critical paths',
		categoryName: 'Technology',
		createdBy: 'performance-engineer',
		resolved: false,
	},
	{
		name: 'Security Patch Management',
		description: 'Delayed application of security patches increasing vulnerability window',
		categoryName: 'Technology',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Technology Skills Gap',
		description: 'Team lacks expertise in required technologies',
		categoryName: 'Technology',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'API Rate Limiting Issues',
		description: 'Third-party APIs rate limiting affecting application functionality',
		categoryName: 'Technology',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Data Backup System Reliability',
		description: 'Backup systems not tested regularly, reliability unknown',
		categoryName: 'Technology',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'Network Infrastructure Outages',
		description: 'Frequent network infrastructure outages affecting service availability',
		categoryName: 'Technology',
		createdBy: 'network-engineer',
		resolved: false,
	},
	{
		name: 'Technology Obsolescence',
		description: 'Key technologies used becoming obsolete',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Integration Testing Gaps',
		description: 'Insufficient integration testing causing production issues',
		categoryName: 'Technology',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Key Employee Retention Risk',
		description: 'High risk of losing key technical talent to competitors',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Skills Gap in Development Team',
		description: 'Development team lacks skills in emerging technologies',
		categoryName: 'Human Resources',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'High Employee Turnover',
		description: 'Employee turnover rate above industry average',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Insufficient Training Programs',
		description: 'Lack of ongoing training programs affecting employee growth',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Remote Work Challenges',
		description: 'Managing remote teams creating communication and productivity issues',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Workplace Safety Concerns',
		description: 'Workplace safety issues requiring immediate attention',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Compensation Competitiveness',
		description: 'Compensation packages not competitive with market rates',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Succession Planning Gaps',
		description: 'No succession plan for critical leadership positions',
		categoryName: 'Human Resources',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Employee Burnout Risk',
		description: 'High workload leading to employee burnout',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Diversity and Inclusion Issues',
		description: 'Workplace diversity and inclusion goals not being met',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Recruitment Pipeline Weakness',
		description: 'Insufficient pipeline of qualified candidates for open positions',
		categoryName: 'Human Resources',
		createdBy: 'recruiting-manager',
		resolved: false,
	},
	{
		name: 'Performance Management System',
		description: 'Performance management system not effectively driving results',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: true,
	},
	{
		name: 'Employee Engagement Decline',
		description: 'Employee engagement scores declining over past quarters',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Labor Law Compliance',
		description: 'Potential violations of labor laws in certain jurisdictions',
		categoryName: 'Human Resources',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Contractor Management Issues',
		description: 'Managing large number of contractors creating operational challenges',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Knowledge Management Gaps',
		description: 'Critical knowledge not properly documented, risking loss',
		categoryName: 'Human Resources',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'Team Collaboration Challenges',
		description: 'Cross-functional teams experiencing collaboration difficulties',
		categoryName: 'Human Resources',
		createdBy: 'project-manager',
		resolved: false,
	},
	{
		name: 'Employee Benefits Costs',
		description: 'Rising employee benefits costs impacting profitability',
		categoryName: 'Human Resources',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Workforce Planning Deficiencies',
		description: 'Inadequate workforce planning for future business needs',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Employee Conflict Resolution',
		description: 'Workplace conflicts not being resolved effectively',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Onboarding Process Inefficiencies',
		description: 'New employee onboarding process taking too long',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: true,
	},
	{
		name: 'Talent Acquisition Costs',
		description: 'High costs associated with recruiting and hiring',
		categoryName: 'Human Resources',
		createdBy: 'recruiting-manager',
		resolved: false,
	},
	{
		name: 'Employee Data Privacy',
		description: 'Employee data handling not compliant with privacy regulations',
		categoryName: 'Human Resources',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Organizational Change Resistance',
		description: 'Employee resistance to organizational changes affecting adoption',
		categoryName: 'Human Resources',
		createdBy: 'change-manager',
		resolved: false,
	},
	{
		name: 'Leadership Development Gaps',
		description: 'Insufficient leadership development programs',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Contract Dispute Risk',
		description: 'Ongoing contract dispute with major vendor',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Intellectual Property Infringement',
		description: 'Potential IP infringement claims from competitors',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Litigation Exposure',
		description: 'Potential litigation from customers or partners',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Terms of Service Issues',
		description: 'Terms of service may not adequately protect company interests',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Employment Law Violations',
		description: 'Potential violations of employment laws',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Data Protection Law Compliance',
		description: 'Data protection practices may violate applicable laws',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Regulatory Investigation Risk',
		description: 'Potential regulatory investigation into business practices',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Contractual Obligation Breaches',
		description: 'Risk of breaching contractual obligations with partners',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Trademark Disputes',
		description: 'Trademark disputes affecting brand protection',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Licensing Agreement Violations',
		description: 'Potential violations of software licensing agreements',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'International Law Compliance',
		description: 'Operations in multiple jurisdictions creating legal complexity',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Privacy Policy Compliance',
		description: 'Privacy policy not fully compliant with all applicable laws',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: true,
	},
	{
		name: 'Product Liability Exposure',
		description: 'Product defects creating potential liability exposure',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Antitrust Compliance',
		description: 'Business practices may raise antitrust concerns',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Shareholder Disputes',
		description: 'Potential disputes with shareholders or investors',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Merger and Acquisition Risks',
		description: 'Legal risks associated with M&A activities',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Securities Law Compliance',
		description: 'Potential securities law violations in fundraising',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Export Control Violations',
		description: 'Potential violations of export control regulations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Consumer Protection Lawsuits',
		description: 'Risk of consumer protection lawsuits',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Insurance Coverage Disputes',
		description: 'Disputes with insurance providers over coverage',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Non-Compete Agreement Enforcement',
		description: 'Challenges enforcing non-compete agreements with former employees',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: true,
	},
	{
		name: 'Regulatory Penalty Risk',
		description: 'Risk of regulatory penalties for non-compliance',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Contract Negotiation Delays',
		description: 'Delays in contract negotiations affecting business operations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Intellectual Property Portfolio Gaps',
		description: 'Insufficient IP protection for key innovations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Cross-Border Legal Issues',
		description: 'Legal complexities in cross-border operations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Carbon Footprint Concerns',
		description: 'High carbon footprint from data center operations',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Energy Consumption',
		description: 'Excessive energy consumption in office and data centers',
		categoryName: 'Environmental',
		createdBy: 'facilities-manager',
		resolved: false,
	},
	{
		name: 'Waste Management Issues',
		description: 'Inadequate waste management and recycling programs',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Water Usage Concerns',
		description: 'High water usage in data center cooling systems',
		categoryName: 'Environmental',
		createdBy: 'facilities-manager',
		resolved: false,
	},
	{
		name: 'E-Waste Disposal',
		description: 'Improper disposal of electronic waste',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Renewable Energy Adoption',
		description: 'Slow adoption of renewable energy sources',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Supply Chain Environmental Impact',
		description: 'Supply chain partners not meeting environmental standards',
		categoryName: 'Environmental',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Climate Change Adaptation',
		description: 'Business operations not adapted to climate change risks',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Environmental Regulatory Compliance',
		description: 'Potential violations of environmental regulations',
		categoryName: 'Environmental',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Sustainable Packaging',
		description: 'Product packaging not using sustainable materials',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: true,
	},
	{
		name: 'Biodiversity Impact',
		description: 'Business operations negatively impacting local biodiversity',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Air Quality Concerns',
		description: 'Office air quality not meeting health standards',
		categoryName: 'Environmental',
		createdBy: 'facilities-manager',
		resolved: false,
	},
	{
		name: 'Resource Depletion',
		description: 'High consumption of non-renewable resources',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Environmental Reporting Gaps',
		description: 'Insufficient environmental impact reporting',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Greenhouse Gas Emissions',
		description: 'High greenhouse gas emissions from operations',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Market Disruption Risk',
		description: 'Emerging technologies disrupting traditional business model',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Competitive Threat',
		description: 'New competitor entering market with superior technology',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Customer Demand Shift',
		description: 'Changing customer preferences affecting product relevance',
		categoryName: 'Strategic',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Technology Disruption',
		description: 'New technology making current solutions obsolete',
		categoryName: 'Strategic',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Business Model Viability',
		description: 'Current business model may not be sustainable long-term',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Market Saturation',
		description: 'Target market becoming saturated, limiting growth',
		categoryName: 'Strategic',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Partnership Dependency',
		description: 'Heavy reliance on strategic partnerships creating vulnerability',
		categoryName: 'Strategic',
		createdBy: 'business-development',
		resolved: false,
	},
	{
		name: 'Product-Market Fit Concerns',
		description: 'Product may not have strong product-market fit',
		categoryName: 'Strategic',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Geographic Expansion Risk',
		description: 'Expansion into new markets facing unexpected challenges',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Innovation Pipeline Weakness',
		description: 'Insufficient innovation pipeline to maintain competitive advantage',
		categoryName: 'Strategic',
		createdBy: 'cto',
		resolved: true,
	},
	{
		name: 'Brand Positioning Challenges',
		description: 'Brand positioning not resonating with target audience',
		categoryName: 'Strategic',
		createdBy: 'marketing-director',
		resolved: false,
	},
	{
		name: 'Customer Acquisition Cost',
		description: 'Customer acquisition costs increasing, affecting profitability',
		categoryName: 'Strategic',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Market Entry Barriers',
		description: 'High barriers to entry in target markets',
		categoryName: 'Strategic',
		createdBy: 'business-development',
		resolved: false,
	},
	{
		name: 'Strategic Planning Gaps',
		description: 'Insufficient strategic planning for future growth',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Competitive Intelligence Gaps',
		description: 'Lack of competitive intelligence affecting strategic decisions',
		categoryName: 'Strategic',
		createdBy: 'business-development',
		resolved: false,
	},
	{
		name: 'Social Media Backlash',
		description: 'Negative social media sentiment affecting brand reputation',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Customer Satisfaction Decline',
		description: 'Declining customer satisfaction scores',
		categoryName: 'Reputational',
		createdBy: 'customer-success',
		resolved: false,
	},
	{
		name: 'Data Breach Publicity',
		description: 'Public disclosure of data breach affecting customer trust',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Product Quality Issues',
		description: 'Product quality issues being reported publicly',
		categoryName: 'Reputational',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Executive Misconduct Allegations',
		description: 'Allegations of executive misconduct affecting company reputation',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Negative Press Coverage',
		description: 'Sustained negative press coverage affecting brand image',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Customer Review Ratings',
		description: 'Declining customer review ratings on public platforms',
		categoryName: 'Reputational',
		createdBy: 'customer-success',
		resolved: false,
	},
	{
		name: 'Vendor Relationship Issues',
		description: 'Public disputes with vendors affecting reputation',
		categoryName: 'Reputational',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Workplace Culture Concerns',
		description: 'Public concerns about workplace culture',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Ethical Business Practices',
		description: 'Questions about ethical business practices',
		categoryName: 'Reputational',
		createdBy: 'ceo',
		resolved: true,
	},
	{
		name: 'Influencer Relationship Damage',
		description: 'Damaged relationships with key industry influencers',
		categoryName: 'Reputational',
		createdBy: 'marketing-director',
		resolved: false,
	},
	{
		name: 'Crisis Communication Gaps',
		description: 'Inadequate crisis communication procedures',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Brand Consistency Issues',
		description: 'Inconsistent brand messaging across channels',
		categoryName: 'Reputational',
		createdBy: 'marketing-director',
		resolved: false,
	},
	{
		name: 'Customer Data Privacy Concerns',
		description: 'Public concerns about customer data privacy practices',
		categoryName: 'Reputational',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Industry Association Standing',
		description: 'Risk to standing in industry associations',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Monolithic Architecture Limitations',
		description: 'Current monolithic architecture limiting scalability and team velocity',
		categoryName: 'Architecture',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Microservices Communication Overhead',
		description: 'Excessive inter-service communication creating performance bottlenecks',
		categoryName: 'Architecture',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Event-Driven Architecture Complexity',
		description: 'Event-driven architecture becoming too complex to debug and maintain',
		categoryName: 'Architecture',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Database Schema Evolution Challenges',
		description: 'Database schema changes causing migration complexity and downtime risk',
		categoryName: 'Architecture',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'API Gateway Performance Issues',
		description: 'API gateway becoming single point of failure and performance bottleneck',
		categoryName: 'Architecture',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Distributed System Consistency',
		description: 'Maintaining data consistency across distributed systems becoming challenging',
		categoryName: 'Architecture',
		createdBy: 'cto',
		resolved: true,
	},
	{
		name: 'AI/ML Model Deployment Pipeline',
		description: 'Lack of robust pipeline for deploying and monitoring ML models in production',
		categoryName: 'Innovation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Blockchain Integration Feasibility',
		description: 'Evaluating blockchain technology for supply chain transparency',
		categoryName: 'Innovation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Quantum Computing Readiness',
		description: 'Preparing for quantum computing impact on current encryption standards',
		categoryName: 'Innovation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Edge Computing Strategy',
		description: 'Developing edge computing strategy to reduce latency and improve performance',
		categoryName: 'Innovation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'AR/VR Technology Adoption',
		description: 'Assessing AR/VR technology for customer engagement and training',
		categoryName: 'Innovation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'IoT Device Integration',
		description: 'Integrating IoT devices into platform architecture',
		categoryName: 'Innovation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Data Lake Architecture Design',
		description: 'Designing scalable data lake architecture for analytics and ML',
		categoryName: 'Data Management',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Real-Time Data Processing',
		description: 'Implementing real-time data processing capabilities for streaming analytics',
		categoryName: 'Data Management',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Data Quality Framework',
		description: 'Establishing comprehensive data quality framework and governance',
		categoryName: 'Data Management',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Master Data Management',
		description: 'Implementing master data management to ensure data consistency',
		categoryName: 'Data Management',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Data Retention and Archival Strategy',
		description: 'Developing strategy for long-term data retention and archival',
		categoryName: 'Data Management',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Data Lineage and Cataloging',
		description: 'Implementing data lineage tracking and cataloging for compliance',
		categoryName: 'Data Management',
		createdBy: 'cto',
		resolved: true,
	},
	{
		name: 'Multi-Cloud Strategy Implementation',
		description: 'Implementing multi-cloud strategy to avoid vendor lock-in',
		categoryName: 'Platform',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Platform Reliability and Uptime',
		description: 'Ensuring 99.99% platform uptime across all services',
		categoryName: 'Platform',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Container Security Hardening',
		description: 'Hardening container security to prevent vulnerabilities',
		categoryName: 'Platform',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Service Mesh Implementation',
		description: 'Implementing service mesh for improved observability and security',
		categoryName: 'Platform',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Platform Cost Optimization',
		description: 'Optimizing cloud platform costs while maintaining performance',
		categoryName: 'Platform',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Vendor Management and SLAs',
		description: 'Managing vendor relationships and ensuring SLA compliance',
		categoryName: 'Platform',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Legacy System Modernization',
		description: 'Modernizing legacy systems to support digital transformation initiatives',
		categoryName: 'Digital Transformation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'API-First Architecture Adoption',
		description: 'Adopting API-first architecture for better integration and scalability',
		categoryName: 'Digital Transformation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'DevOps Culture Transformation',
		description: 'Transforming organizational culture to embrace DevOps practices',
		categoryName: 'Digital Transformation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Cloud Migration Strategy',
		description: 'Executing comprehensive cloud migration strategy for all workloads',
		categoryName: 'Digital Transformation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Low-Code/No-Code Platform Evaluation',
		description: 'Evaluating low-code/no-code platforms to accelerate development',
		categoryName: 'Digital Transformation',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Customer Experience Technology Stack',
		description: 'Building integrated technology stack for seamless customer experience',
		categoryName: 'Digital Transformation',
		createdBy: 'cto',
		resolved: true,
	},
	{
		name: 'Zero-Day Vulnerability Exposure',
		description: 'Application vulnerable to unknown zero-day exploits',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'DDoS Attack Vulnerability',
		description: 'Infrastructure vulnerable to distributed denial of service attacks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Man-in-the-Middle Attack Risk',
		description: 'Network communications vulnerable to interception attacks',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Phishing Attack Susceptibility',
		description: 'Employees vulnerable to phishing attacks due to insufficient training',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Ransomware Protection Gaps',
		description: 'Insufficient protection against ransomware attacks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Awareness Training Deficiencies',
		description: 'Employees lack sufficient security awareness training',
		categoryName: 'Security',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Vulnerability Scanning Gaps',
		description: 'Insufficient vulnerability scanning and assessment processes',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Penetration Testing Inadequacy',
		description: 'Penetration testing not conducted regularly or comprehensively',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Security Incident Response Delays',
		description: 'Security incident response procedures not well-defined or tested',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Third-Party Security Assessment Gaps',
		description: 'Third-party vendors not properly assessed for security risks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Policy Enforcement Weakness',
		description: 'Security policies not consistently enforced across organization',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Encryption Key Management Issues',
		description: 'Encryption keys not properly managed or rotated',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Monitoring Blind Spots',
		description: 'Security monitoring systems have blind spots in coverage',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Identity Management System Flaws',
		description: 'Identity and access management system has design flaws',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Architecture Weaknesses',
		description: 'Overall security architecture has fundamental weaknesses',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Mobile Device Security Gaps',
		description: 'Mobile devices accessing corporate resources lack proper security controls',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Cloud Security Configuration Errors',
		description: 'Cloud infrastructure misconfigured, exposing security vulnerabilities',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'Security Compliance Audit Failures',
		description: 'Failed security compliance audits indicating systemic issues',
		categoryName: 'Security',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Security Training Program Inadequacy',
		description: 'Security training programs not effective in reducing human error risks',
		categoryName: 'Security',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Security Budget Constraints',
		description: 'Insufficient budget allocated for security improvements',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Tool Integration Issues',
		description: 'Security tools not properly integrated, creating visibility gaps',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Metrics and Reporting Gaps',
		description: 'Lack of comprehensive security metrics and reporting',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Vendor Dependency Risks',
		description: 'Over-reliance on single security vendor creating lock-in risks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Documentation Incompleteness',
		description: 'Security documentation incomplete or outdated',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Change Management Weakness',
		description: 'Security changes not properly managed or reviewed',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Risk Assessment Gaps',
		description: 'Security risk assessments not conducted regularly or comprehensively',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Security Architecture Review Deficiencies',
		description: 'Security architecture reviews not conducted regularly',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Security Awareness Program Weakness',
		description: 'Security awareness programs not engaging or effective',
		categoryName: 'Security',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Security Incident Recovery Planning',
		description: 'Insufficient planning for security incident recovery',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Compliance Monitoring Gaps',
		description: 'Security compliance not continuously monitored',
		categoryName: 'Security',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Security Testing Automation Gaps',
		description: 'Security testing not sufficiently automated in CI/CD pipeline',
		categoryName: 'Security',
		createdBy: 'devops-team',
		resolved: false,
	},
	{
		name: 'Security Data Classification Errors',
		description: 'Data not properly classified, leading to inappropriate security controls',
		categoryName: 'Security',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Security Perimeter Weakness',
		description: 'Network security perimeter has weaknesses or gaps',
		categoryName: 'Security',
		createdBy: 'network-engineer',
		resolved: false,
	},
	{
		name: 'Security Patch Deployment Delays',
		description: 'Security patches not deployed in timely manner',
		categoryName: 'Security',
		createdBy: 'devops-team',
		resolved: false,
	},
	{
		name: 'Security Configuration Drift',
		description: 'Security configurations drifting from baseline over time',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'Security Tool False Positives',
		description: 'Security tools generating too many false positives, reducing effectiveness',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Incident Communication Gaps',
		description: 'Security incident communication procedures not well-defined',
		categoryName: 'Security',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Security Vendor Security Assessment',
		description: 'Security vendors not properly assessed for their own security practices',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Architecture Scalability Issues',
		description: 'Security architecture not scaling with business growth',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Security Training Content Outdated',
		description: 'Security training content not updated with latest threats',
		categoryName: 'Security',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Security Metrics Dashboard Inadequacy',
		description: 'Security metrics dashboards not providing actionable insights',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Compliance Reporting Delays',
		description: 'Security compliance reporting delayed or incomplete',
		categoryName: 'Security',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Security Tool License Expiration Risk',
		description: 'Security tool licenses expiring without renewal planning',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Staff Skill Gaps',
		description: 'Security staff lack skills in emerging security technologies',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Security Budget Allocation Issues',
		description: 'Security budget not optimally allocated across security domains',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Service Level Agreement Breaches',
		description: 'Frequent SLA breaches affecting customer satisfaction',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Capacity Planning Inaccuracy',
		description: 'Capacity planning models not accurately predicting resource needs',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Change Management Process Gaps',
		description: 'Change management process not effectively preventing incidents',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Root Cause Analysis Inadequacy',
		description: 'Root cause analysis not identifying true underlying issues',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Post-Incident Review Deficiencies',
		description: 'Post-incident reviews not leading to effective preventive measures',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Runbook Completeness',
		description: 'Operational runbooks incomplete or outdated',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'On-Call Rotation Burnout',
		description: 'On-call rotation causing team burnout and reduced effectiveness',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Knowledge Silos',
		description: 'Operational knowledge concentrated in few individuals',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Dependency Mapping Gaps',
		description: 'Service dependency mapping incomplete, affecting incident response',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Metrics Inadequacy',
		description: 'Operational metrics not providing actionable insights',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Catalog Incompleteness',
		description: 'Service catalog incomplete, affecting service delivery',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Process Automation Gaps',
		description: 'Operational processes not sufficiently automated',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Request Fulfillment Delays',
		description: 'Service request fulfillment taking longer than expected',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Tool Integration Issues',
		description: 'Operational tools not properly integrated, creating inefficiencies',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Availability Target Misses',
		description: 'Service availability targets consistently not being met',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Cost Overruns',
		description: 'Operational costs exceeding budget allocations',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Performance Degradation',
		description: 'Service performance degrading over time without clear cause',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Staffing Shortages',
		description: 'Insufficient operational staff to handle workload',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Transition Planning Gaps',
		description: 'Service transition from development to operations not well-planned',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Vendor Management Issues',
		description: 'Operational vendors not meeting performance expectations',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Continuity Planning Inadequacy',
		description: 'Service continuity planning not comprehensive enough',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Data Quality Issues',
		description: 'Operational data quality issues affecting decision-making',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Level Management Gaps',
		description: 'Service level management not effectively tracking and improving SLAs',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Process Standardization',
		description: 'Operational processes not standardized across teams',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Capacity Exhaustion Risk',
		description: 'Service capacity approaching limits without expansion plans',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Tool License Expiration',
		description: 'Operational tool licenses expiring without renewal planning',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Dependency Chain Complexity',
		description: 'Service dependency chains becoming too complex to manage',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Incident Escalation Issues',
		description: 'Incident escalation procedures not working effectively',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Monitoring Coverage Gaps',
		description: 'Service monitoring not covering all critical components',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Budget Planning Inaccuracy',
		description: 'Operational budget planning not accurately forecasting needs',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Release Management Issues',
		description: 'Service release management process causing operational issues',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Staff Training Gaps',
		description: 'Operational staff training not keeping pace with technology changes',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Configuration Drift',
		description: 'Service configurations drifting from intended state',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Tool Performance Issues',
		description: 'Operational tools experiencing performance problems',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Availability Monitoring Gaps',
		description: 'Service availability monitoring not comprehensive',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Process Documentation Gaps',
		description: 'Operational process documentation incomplete or outdated',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Performance Benchmarking',
		description: 'Service performance not benchmarked against industry standards',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Cost Optimization Opportunities',
		description: 'Operational costs not optimized, missing cost-saving opportunities',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Dependency Risk Assessment',
		description: 'Service dependency risks not regularly assessed',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Tool Integration Complexity',
		description: 'Operational tool integration becoming too complex to maintain',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Level Agreement Negotiation',
		description: 'Service level agreements not properly negotiated with stakeholders',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Incident Response Time',
		description: 'Incident response times not meeting targets',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Capacity Planning Inadequacy',
		description: 'Service capacity planning not accounting for growth scenarios',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Vendor Performance Monitoring',
		description: 'Operational vendor performance not effectively monitored',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Continuity Testing Gaps',
		description: 'Service continuity plans not regularly tested',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Process Improvement Stagnation',
		description: 'Operational process improvement initiatives not progressing',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Monitoring Alert Fatigue',
		description: 'Service monitoring generating too many alerts, causing fatigue',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Operational Knowledge Transfer Issues',
		description: 'Operational knowledge not effectively transferred between team members',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Level Reporting Inadequacy',
		description: 'Service level reporting not providing actionable insights',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Cash Flow Forecasting Inaccuracy',
		description: 'Cash flow forecasts not accurately predicting actual cash flows',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Delays',
		description: 'Financial reporting delayed, affecting decision-making',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Budget Variance Analysis Gaps',
		description: 'Budget variances not properly analyzed or explained',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Integration Issues',
		description: 'Financial systems not properly integrated, causing data inconsistencies',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Data Quality Issues',
		description: 'Financial data quality issues affecting reporting accuracy',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Automation Gaps',
		description: 'Financial processes not sufficiently automated',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Audit Preparation Inadequacy',
		description: 'Financial audit preparation not comprehensive enough',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Risk Assessment Gaps',
		description: 'Financial risks not regularly assessed or updated',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Planning Process Weakness',
		description: 'Financial planning process not effectively supporting strategic decisions',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Security Gaps',
		description: 'Financial systems have security vulnerabilities',
		categoryName: 'Financial',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Financial Compliance Monitoring',
		description: 'Financial compliance not continuously monitored',
		categoryName: 'Financial',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Financial Vendor Payment Processing',
		description: 'Vendor payment processing experiencing delays or errors',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Accuracy',
		description: 'Financial reporting accuracy concerns identified',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Backup Inadequacy',
		description: 'Financial system backups not comprehensive or tested',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Documentation Gaps',
		description: 'Financial process documentation incomplete or outdated',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Staff Training Needs',
		description: 'Financial staff need additional training on new systems or processes',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Performance Issues',
		description: 'Financial systems experiencing performance problems',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Data Archival Strategy',
		description: 'Financial data archival strategy not defined or implemented',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Automation',
		description: 'Financial reporting not sufficiently automated',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Risk Monitoring Gaps',
		description: 'Financial risk monitoring not comprehensive',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Upgrade Risks',
		description: 'Financial system upgrades posing risks to operations',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Standardization',
		description: 'Financial processes not standardized across departments',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Data Integration Challenges',
		description: 'Financial data integration from multiple sources challenging',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Timeliness',
		description: 'Financial reporting not delivered in timely manner',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Access Control',
		description: 'Financial system access controls not properly managed',
		categoryName: 'Financial',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Financial Process Efficiency',
		description: 'Financial processes not operating efficiently',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Budget Tracking Inadequacy',
		description: 'Budget tracking not providing real-time visibility',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Disaster Recovery',
		description: 'Financial system disaster recovery plans not tested',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Vendor Management',
		description: 'Financial vendors not effectively managed',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Format Issues',
		description: 'Financial reporting formats not meeting stakeholder needs',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Scalability',
		description: 'Financial systems not scaling with business growth',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Improvement Stagnation',
		description: 'Financial process improvement initiatives not progressing',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Data Retention Compliance',
		description: 'Financial data retention not compliant with regulations',
		categoryName: 'Financial',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Financial System Integration Testing',
		description: 'Financial system integration testing not comprehensive',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Dashboard Inadequacy',
		description: 'Financial reporting dashboards not providing actionable insights',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Risk Modeling Accuracy',
		description: 'Financial risk models not accurately predicting outcomes',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System User Training',
		description: 'Financial system users need additional training',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Workflow Issues',
		description: 'Financial process workflows not optimized',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Data Validation Gaps',
		description: 'Financial data validation not comprehensive enough',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Maintenance Windows',
		description: 'Financial system maintenance windows causing business disruption',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Reporting Distribution Issues',
		description: 'Financial reporting distribution not reaching all stakeholders',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Approval Delays',
		description: 'Financial process approvals taking too long',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Performance Monitoring',
		description: 'Financial system performance not effectively monitored',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Budget Allocation Optimization',
		description: 'Budget allocation not optimized across departments',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Risk Communication Gaps',
		description: 'Financial risks not effectively communicated to stakeholders',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial System Change Management',
		description: 'Financial system changes not properly managed',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Financial Process Compliance Monitoring',
		description: 'Financial process compliance not continuously monitored',
		categoryName: 'Financial',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Financial Data Backup Verification',
		description: 'Financial data backups not regularly verified',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Compliance Training Inadequacy',
		description: 'Compliance training not comprehensive or effective',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Monitoring Automation Gaps',
		description: 'Compliance monitoring not sufficiently automated',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Documentation Gaps',
		description: 'Compliance documentation incomplete or outdated',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Assessment Frequency',
		description: 'Compliance risk assessments not conducted frequently enough',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Delays',
		description: 'Compliance reporting delayed, affecting regulatory submissions',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Standardization',
		description: 'Compliance processes not standardized across departments',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Integration Issues',
		description: 'Compliance systems not properly integrated',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Staff Training Needs',
		description: 'Compliance staff need additional training on new regulations',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Audit Preparation Inadequacy',
		description: 'Compliance audit preparation not comprehensive',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Communication Gaps',
		description: 'Compliance risks not effectively communicated to management',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Policy Enforcement Weakness',
		description: 'Compliance policies not consistently enforced',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Monitoring Coverage Gaps',
		description: 'Compliance monitoring not covering all required areas',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Accuracy',
		description: 'Compliance reporting accuracy concerns identified',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Automation Opportunities',
		description: 'Compliance processes not sufficiently automated',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Performance Issues',
		description: 'Compliance systems experiencing performance problems',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Data Quality Issues',
		description: 'Compliance data quality issues affecting reporting',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Training Content Updates',
		description: 'Compliance training content not updated with latest regulations',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Assessment Methodology',
		description: 'Compliance risk assessment methodology needs improvement',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Format Issues',
		description: 'Compliance reporting formats not meeting regulatory requirements',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Documentation Inadequacy',
		description: 'Compliance process documentation not comprehensive enough',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Backup Inadequacy',
		description: 'Compliance system backups not comprehensive or tested',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Staff Resource Constraints',
		description: 'Compliance staff resources insufficient for workload',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Monitoring Tool Gaps',
		description: 'Compliance monitoring tools not meeting needs',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Prioritization',
		description: 'Compliance risks not effectively prioritized',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Distribution',
		description: 'Compliance reporting not reaching all required stakeholders',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Improvement Stagnation',
		description: 'Compliance process improvement initiatives not progressing',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Integration Testing',
		description: 'Compliance system integration testing not comprehensive',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Training Effectiveness',
		description: 'Compliance training not effectively reducing violations',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Communication Timeliness',
		description: 'Compliance risks not communicated in timely manner',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Policy Update Frequency',
		description: 'Compliance policies not updated frequently enough',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Monitoring Alert Fatigue',
		description: 'Compliance monitoring generating too many alerts',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Scalability',
		description: 'Compliance systems not scaling with business growth',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Data Retention Management',
		description: 'Compliance data retention not properly managed',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Workflow Issues',
		description: 'Compliance process workflows not optimized',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Dashboard Inadequacy',
		description: 'Compliance reporting dashboards not providing actionable insights',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Assessment Coverage',
		description: 'Compliance risk assessments not covering all areas',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System User Training',
		description: 'Compliance system users need additional training',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Approval Delays',
		description: 'Compliance process approvals taking too long',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Monitoring Performance',
		description: 'Compliance monitoring performance not meeting targets',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Change Management',
		description: 'Compliance system changes not properly managed',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Data Validation Gaps',
		description: 'Compliance data validation not comprehensive enough',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Timeliness',
		description: 'Compliance reporting not delivered in timely manner',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Assessment Accuracy',
		description: 'Compliance risk assessments not accurately identifying risks',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Disaster Recovery',
		description: 'Compliance system disaster recovery plans not tested',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Efficiency',
		description: 'Compliance processes not operating efficiently',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Monitoring Coverage Expansion',
		description: 'Compliance monitoring coverage needs expansion',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Reporting Automation',
		description: 'Compliance reporting not sufficiently automated',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Risk Communication Effectiveness',
		description: 'Compliance risk communication not effectively reaching stakeholders',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance System Maintenance Windows',
		description: 'Compliance system maintenance windows causing business disruption',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Compliance Process Knowledge Management',
		description: 'Compliance process knowledge not effectively managed',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
];

async function seedDatabase(): Promise<void> {
	try {
		// Connect to database
		await connectDB();

		// Clear existing data
		console.log('Clearing existing data...');
		await Risk.deleteMany({});
		await Category.deleteMany({});
		console.log('Existing data cleared.');

		// Create categories
		console.log('Creating categories...');
		const createdCategories = await Category.insertMany(categoriesData);
		console.log(`Created ${createdCategories.length} categories.`);

		// Create a map of category names to IDs
		const categoryMap: Record<string, mongoose.Types.ObjectId> = {};
		createdCategories.forEach((cat) => {
			categoryMap[cat.name] = cat._id;
		});

		// Create risks with category references
		console.log('Creating risks...');
		const risksToInsert = risksData.map((risk) => ({
			name: risk.name,
			description: risk.description,
			categoryId: categoryMap[risk.categoryName],
			createdBy: risk.createdBy,
			resolved: risk.resolved || false,
		}));

		const additionalRisks = generateRandomRisks(600, createdCategories);
		const allRisksToInsert = [...risksToInsert, ...additionalRisks];

		const createdRisks = await Risk.insertMany(allRisksToInsert);
		console.log(`Created ${createdRisks.length} risks.`);

		// Display summary
		console.log('\n=== Seeding Summary ===');
		console.log(`Categories created: ${createdCategories.length}`);
		console.log(`Risks created: ${createdRisks.length}`);
		console.log(`\nRisks by category:`);
		const risksByCategory = createdRisks.reduce((acc: Record<string, number>, risk) => {
			const key = risk.categoryId.toString();
			acc[key] = (acc[key] || 0) + 1;
			return acc;
		}, {});

		createdCategories.forEach((cat) => {
			const count = risksByCategory[cat._id.toString()] || 0;
			console.log(`  ${cat.name}: ${count}`);
		});

		const resolvedCount = createdRisks.filter((r) => r.resolved).length;
		console.log(`\nResolved risks: ${resolvedCount}`);
		console.log(`Unresolved risks: ${createdRisks.length - resolvedCount}`);

		console.log('\n✅ Database seeded successfully!');
		process.exit(0);
	} catch (error) {
		const errorMessage = error instanceof Error ? error.message : 'Unknown error';
		console.error('❌ Error seeding database:', errorMessage);
		process.exit(1);
	}
}

seedDatabase();
