import 'dotenv/config';
import { Risk } from '../models/risk.js';
import { Category } from '../models/category.js';
import connectDB from '../db.js';

const categoriesData = [
	{
		name: 'Security',
		description: 'Security-related risks including vulnerabilities, breaches, and access control issues',
		createdBy: 'security-team',
	},
	{
		name: 'Operational',
		description: 'Operational risks including system failures, process inefficiencies, and resource constraints',
		createdBy: 'operations-team',
	},
	{
		name: 'Financial',
		description: 'Financial risks including budget overruns, cost management, and revenue impacts',
		createdBy: 'finance-team',
	},
	{
		name: 'Compliance',
		description: 'Compliance risks including regulatory violations, audit failures, and legal requirements',
		createdBy: 'compliance-officer',
	},
	{
		name: 'Technology',
		description: 'Technology risks including infrastructure failures, technical debt, and integration issues',
		createdBy: 'cto',
	},
	{
		name: 'Human Resources',
		description: 'HR risks including talent retention, skill gaps, and organizational changes',
		createdBy: 'hr-director',
	},
	{
		name: 'Legal',
		description: 'Legal risks including contract disputes, intellectual property issues, and litigation',
		createdBy: 'legal-counsel',
	},
	{
		name: 'Environmental',
		description: 'Environmental risks including sustainability concerns, resource consumption, and climate impact',
		createdBy: 'sustainability-manager',
	},
	{
		name: 'Strategic',
		description: 'Strategic risks including market changes, competitive threats, and business model disruptions',
		createdBy: 'ceo',
	},
	{
		name: 'Reputational',
		description: 'Reputational risks including brand damage, public relations issues, and customer trust',
		createdBy: 'pr-manager',
	},
	{
		name: 'Architecture',
		description: 'System architecture risks including scalability, maintainability, and design decisions',
		createdBy: 'cto',
	},
	{
		name: 'Innovation',
		description: 'Innovation risks including R&D investments, technology adoption, and competitive differentiation',
		createdBy: 'cto',
	},
	{
		name: 'Data Management',
		description: 'Data management risks including data quality, governance, and lifecycle management',
		createdBy: 'cto',
	},
	{
		name: 'Platform',
		description: 'Platform risks including infrastructure reliability, vendor management, and service delivery',
		createdBy: 'cto',
	},
	{
		name: 'Digital Transformation',
		description: 'Digital transformation risks including change management, technology integration, and process modernization',
		createdBy: 'cto',
	},
	{
		name: 'Quality Assurance',
		description: 'Quality assurance risks including testing gaps, defect management, and quality control processes',
		createdBy: 'qa-manager',
	},
];

const risksData = [
	// Security Risks (10 risks)
	{
		name: 'SQL Injection Vulnerability',
		description: 'Database queries are vulnerable to SQL injection attacks due to improper input sanitization',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Weak Password Policy',
		description: 'Current password policy allows weak passwords, increasing risk of unauthorized access',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Missing SSL/TLS Certificate',
		description: 'API endpoints are not using SSL/TLS encryption, exposing data in transit',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: true,
	},
	{
		name: 'Unauthorized API Access',
		description: 'API endpoints lack proper authentication mechanisms, allowing unauthorized access',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Cross-Site Scripting (XSS)',
		description: 'User input is not properly sanitized, allowing potential XSS attacks in web interface',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Outdated Dependencies',
		description: 'Multiple npm packages contain known security vulnerabilities and need updates',
		categoryName: 'Security',
		createdBy: 'security-scanner',
		resolved: false,
	},
	{
		name: 'Exposed API Keys',
		description: 'API keys found in public repository, requiring immediate rotation and removal',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: true,
	},
	{
		name: 'Insufficient Logging',
		description: 'Security events are not properly logged, making incident detection difficult',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Missing Rate Limiting',
		description: 'API endpoints lack rate limiting, vulnerable to brute force and DDoS attacks',
		categoryName: 'Security',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Insecure Data Storage',
		description: 'Sensitive user data stored in plaintext instead of encrypted format',
		categoryName: 'Security',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	// Operational Risks (10 risks)
	{
		name: 'Database Performance Degradation',
		description: 'Query response times have increased by 300% over the past month, affecting user experience',
		categoryName: 'Operational',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Single Point of Failure',
		description: 'Application relies on single database server without redundancy or failover mechanism',
		categoryName: 'Operational',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Insufficient Backup Strategy',
		description: 'Current backup frequency is weekly, which may result in significant data loss in case of failure',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'High Server Load',
		description: 'CPU usage consistently above 85% during peak hours, risking service degradation',
		categoryName: 'Operational',
		createdBy: 'monitoring-system',
		resolved: false,
	},
	{
		name: 'Memory Leak in Production',
		description: 'Application memory usage gradually increases over time, requiring periodic restarts',
		categoryName: 'Operational',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Missing Error Handling',
		description: 'Several API endpoints lack proper error handling, causing unhandled exceptions',
		categoryName: 'Operational',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Monitoring',
		description: 'No comprehensive monitoring system in place, making issue detection reactive rather than proactive',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Outdated Documentation',
		description: 'API documentation is outdated and does not reflect current implementation, causing integration issues',
		categoryName: 'Operational',
		createdBy: 'technical-writer',
		resolved: true,
	},
	{
		name: 'Resource Exhaustion Risk',
		description: 'Disk space usage growing at 10GB per week, may reach capacity within 2 months',
		categoryName: 'Operational',
		createdBy: 'system-admin',
		resolved: false,
	},
	{
		name: 'Third-Party Service Dependency',
		description: 'Critical functionality depends on external service with 99% uptime SLA, creating reliability risk',
		categoryName: 'Operational',
		createdBy: 'product-manager',
		resolved: false,
	},
	// Additional Security Risks (20 more)
	{
		name: 'Privilege Escalation Vulnerability',
		description: 'Users can escalate privileges through application logic flaw',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Session Hijacking Risk',
		description: 'Session tokens not properly secured, vulnerable to hijacking attacks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Insecure Direct Object Reference',
		description: 'Application exposes internal object references without proper authorization checks',
		categoryName: 'Security',
		createdBy: 'security-scanner',
		resolved: false,
	},
	{
		name: 'CSRF Protection Missing',
		description: 'Forms lack CSRF tokens, vulnerable to cross-site request forgery',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: true,
	},
	{
		name: 'Insecure File Upload',
		description: 'File upload functionality allows malicious file execution',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Broken Authentication',
		description: 'Authentication mechanism has flaws allowing bypass or brute force attacks',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Sensitive Data Exposure',
		description: 'Application logs contain sensitive information in plaintext',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'XML External Entity Injection',
		description: 'XML processors vulnerable to XXE attacks, allowing file system access',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Insecure Deserialization',
		description: 'Deserialization of untrusted data can lead to remote code execution',
		categoryName: 'Security',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Using Components with Known Vulnerabilities',
		description: 'Third-party libraries contain unpatched security vulnerabilities',
		categoryName: 'Security',
		createdBy: 'security-scanner',
		resolved: false,
	},
	{
		name: 'Insufficient Security Logging',
		description: 'Security events not logged with sufficient detail for forensic analysis',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Weak Encryption Algorithms',
		description: 'Application uses deprecated encryption algorithms vulnerable to attacks',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: true,
	},
	{
		name: 'Missing Security Headers',
		description: 'HTTP security headers not configured, increasing attack surface',
		categoryName: 'Security',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'Insecure API Design',
		description: 'API endpoints expose sensitive operations without proper authentication',
		categoryName: 'Security',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Hardcoded Credentials',
		description: 'Application code contains hardcoded passwords and API keys',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Insufficient Input Validation',
		description: 'User inputs not properly validated, allowing malicious payloads',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Missing Multi-Factor Authentication',
		description: 'Critical accounts lack MFA, increasing risk of unauthorized access',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Insecure Cookie Configuration',
		description: 'Cookies not marked as secure or HttpOnly, vulnerable to theft',
		categoryName: 'Security',
		createdBy: 'frontend-developer',
		resolved: true,
	},
	{
		name: 'Insufficient Access Controls',
		description: 'Role-based access controls not properly implemented across all endpoints',
		categoryName: 'Security',
		createdBy: 'security-auditor',
		resolved: false,
	},
	{
		name: 'Vulnerable Third-Party Integrations',
		description: 'Third-party services integrated without proper security assessment',
		categoryName: 'Security',
		createdBy: 'security-team',
		resolved: false,
	},
	// Additional Operational Risks (20 more)
	{
		name: 'Network Latency Issues',
		description: 'High network latency affecting application performance in certain regions',
		categoryName: 'Operational',
		createdBy: 'network-engineer',
		resolved: false,
	},
	{
		name: 'Insufficient Load Testing',
		description: 'Application not tested under production load conditions',
		categoryName: 'Operational',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Database Connection Pool Exhaustion',
		description: 'Database connection pool frequently exhausted, causing request failures',
		categoryName: 'Operational',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Missing Disaster Recovery Plan',
		description: 'No documented disaster recovery procedures in place',
		categoryName: 'Operational',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Capacity Planning',
		description: 'No capacity planning process, risking resource shortages during growth',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Degradation During Peak Hours',
		description: 'Application performance degrades significantly during peak usage periods',
		categoryName: 'Operational',
		createdBy: 'monitoring-system',
		resolved: false,
	},
	{
		name: 'Incomplete Deployment Procedures',
		description: 'Deployment process lacks proper rollback mechanisms and testing',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'Missing Health Check Endpoints',
		description: 'No health check endpoints for monitoring application status',
		categoryName: 'Operational',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Inefficient Database Queries',
		description: 'Multiple queries lack proper indexing, causing slow response times',
		categoryName: 'Operational',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Insufficient Logging Infrastructure',
		description: 'Logging system cannot handle peak load, causing log loss',
		categoryName: 'Operational',
		createdBy: 'devops-engineer',
		resolved: false,
	},
	{
		name: 'Missing Automated Testing',
		description: 'Critical functionality lacks automated tests, increasing regression risk',
		categoryName: 'Operational',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Alerting System',
		description: 'Alerting system generates too many false positives, reducing effectiveness',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Version Control Issues',
		description: 'Code repository lacks proper branching strategy and code review process',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: false,
	},
	{
		name: 'Insufficient Scalability',
		description: 'Application architecture cannot scale horizontally to meet demand',
		categoryName: 'Operational',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Missing Performance Benchmarks',
		description: 'No performance benchmarks established, making optimization difficult',
		categoryName: 'Operational',
		createdBy: 'performance-engineer',
		resolved: false,
	},
	{
		name: 'Inadequate Change Management',
		description: 'No formal change management process, increasing deployment risks',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Service Dependency Chain Risk',
		description: 'Critical service depends on multiple other services, creating cascade failure risk',
		categoryName: 'Operational',
		createdBy: 'system-architect',
		resolved: false,
	},
	{
		name: 'Missing Configuration Management',
		description: 'Application configurations not properly versioned or managed',
		categoryName: 'Operational',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'Insufficient Incident Response',
		description: 'No documented incident response procedures for production issues',
		categoryName: 'Operational',
		createdBy: 'operations-manager',
		resolved: false,
	},
	{
		name: 'Legacy System Integration Issues',
		description: 'Integration with legacy systems causing performance and reliability problems',
		categoryName: 'Operational',
		createdBy: 'integration-engineer',
		resolved: false,
	},
	// Financial Risks (25 risks)
	{
		name: 'Budget Overrun Risk',
		description: 'Project costs exceeding allocated budget by 15%',
		categoryName: 'Financial',
		createdBy: 'project-manager',
		resolved: false,
	},
	{
		name: 'Unexpected Infrastructure Costs',
		description: 'Cloud infrastructure costs 40% higher than projected',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Currency Exchange Rate Volatility',
		description: 'International operations exposed to currency fluctuation risks',
		categoryName: 'Financial',
		createdBy: 'finance-director',
		resolved: false,
	},
	{
		name: 'Payment Processing Fees',
		description: 'High payment processing fees reducing profit margins',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Delayed Revenue Recognition',
		description: 'Revenue recognition delays affecting cash flow projections',
		categoryName: 'Financial',
		createdBy: 'accounting-manager',
		resolved: false,
	},
	{
		name: 'Insufficient Financial Reserves',
		description: 'Company lacks adequate financial reserves for unexpected expenses',
		categoryName: 'Financial',
		createdBy: 'cfo',
		resolved: false,
	},
	{
		name: 'Tax Compliance Issues',
		description: 'Potential tax compliance issues in new markets',
		categoryName: 'Financial',
		createdBy: 'tax-advisor',
		resolved: false,
	},
	{
		name: 'Vendor Payment Delays',
		description: 'Delays in vendor payments affecting supplier relationships',
		categoryName: 'Financial',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Investment Portfolio Risk',
		description: 'Company investments exposed to market volatility',
		categoryName: 'Financial',
		createdBy: 'finance-director',
		resolved: false,
	},
	{
		name: 'Credit Risk Exposure',
		description: 'High exposure to customer credit defaults',
		categoryName: 'Financial',
		createdBy: 'credit-manager',
		resolved: false,
	},
	{
		name: 'Inflation Impact on Costs',
		description: 'Rising inflation increasing operational costs faster than revenue',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Fraud Detection Gaps',
		description: 'Insufficient fraud detection mechanisms in payment systems',
		categoryName: 'Financial',
		createdBy: 'security-team',
		resolved: true,
	},
	{
		name: 'Subscription Revenue Churn',
		description: 'High customer churn rate affecting recurring revenue',
		categoryName: 'Financial',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Regulatory Fine Risk',
		description: 'Potential regulatory fines for non-compliance',
		categoryName: 'Financial',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Insurance Coverage Gaps',
		description: 'Insufficient insurance coverage for key business risks',
		categoryName: 'Financial',
		createdBy: 'risk-manager',
		resolved: false,
	},
	{
		name: 'Cost Overrun in Development',
		description: 'Software development costs exceeding estimates',
		categoryName: 'Financial',
		createdBy: 'project-manager',
		resolved: false,
	},
	{
		name: 'Market Downturn Impact',
		description: 'Economic downturn affecting customer spending',
		categoryName: 'Financial',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Inadequate Pricing Strategy',
		description: 'Current pricing model not covering full cost structure',
		categoryName: 'Financial',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Foreign Exchange Losses',
		description: 'Unhedged foreign currency exposure causing losses',
		categoryName: 'Financial',
		createdBy: 'finance-director',
		resolved: false,
	},
	{
		name: 'Insufficient Working Capital',
		description: 'Working capital constraints limiting growth opportunities',
		categoryName: 'Financial',
		createdBy: 'cfo',
		resolved: false,
	},
	{
		name: 'Revenue Recognition Compliance',
		description: 'Complex revenue recognition requirements causing accounting challenges',
		categoryName: 'Financial',
		createdBy: 'accounting-manager',
		resolved: true,
	},
	{
		name: 'Customer Payment Terms Risk',
		description: 'Extended payment terms increasing cash flow risk',
		categoryName: 'Financial',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Technology Investment ROI',
		description: 'Technology investments not delivering expected returns',
		categoryName: 'Financial',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Competitive Pricing Pressure',
		description: 'Competitors forcing price reductions, impacting margins',
		categoryName: 'Financial',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Inadequate Financial Controls',
		description: 'Weak internal financial controls increasing fraud risk',
		categoryName: 'Financial',
		createdBy: 'internal-auditor',
		resolved: false,
	},
	// Compliance Risks (25 risks)
	{
		name: 'GDPR Compliance Gaps',
		description: 'Data processing activities not fully compliant with GDPR requirements',
		categoryName: 'Compliance',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'HIPAA Violation Risk',
		description: 'Healthcare data handling may violate HIPAA regulations',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'PCI DSS Non-Compliance',
		description: 'Payment card data processing not meeting PCI DSS standards',
		categoryName: 'Compliance',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'SOX Compliance Issues',
		description: 'Financial reporting controls not meeting SOX requirements',
		categoryName: 'Compliance',
		createdBy: 'internal-auditor',
		resolved: false,
	},
	{
		name: 'Missing Privacy Policy Updates',
		description: 'Privacy policy not updated to reflect current data practices',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Insufficient Audit Trail',
		description: 'System lacks comprehensive audit trail for compliance requirements',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Data Retention Policy Violations',
		description: 'Data retention practices not aligned with regulatory requirements',
		categoryName: 'Compliance',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Export Control Compliance',
		description: 'Software exports may violate international trade regulations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Accessibility Compliance Gaps',
		description: 'Application not meeting WCAG accessibility standards',
		categoryName: 'Compliance',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Industry-Specific Regulations',
		description: 'New industry regulations requiring system modifications',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Third-Party Compliance Risk',
		description: 'Vendors not meeting required compliance standards',
		categoryName: 'Compliance',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Data Breach Notification Requirements',
		description: 'Insufficient procedures for timely data breach notifications',
		categoryName: 'Compliance',
		createdBy: 'security-team',
		resolved: true,
	},
	{
		name: 'Cross-Border Data Transfer Issues',
		description: 'Data transfers to certain countries may violate regulations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Employee Data Protection',
		description: 'Employee data handling not compliant with labor regulations',
		categoryName: 'Compliance',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Financial Services Regulations',
		description: 'Operations may require financial services licensing',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Environmental Regulations',
		description: 'Operations not compliant with environmental regulations',
		categoryName: 'Compliance',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Consumer Protection Laws',
		description: 'Product features may violate consumer protection regulations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Anti-Money Laundering Requirements',
		description: 'Payment processing may require AML compliance measures',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Licensing and Permits',
		description: 'Missing required business licenses and permits',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Record Keeping Requirements',
		description: 'Insufficient record keeping for regulatory compliance',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Regulatory Change Management',
		description: 'No process for tracking and implementing regulatory changes',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: true,
	},
	{
		name: 'Contract Compliance Issues',
		description: 'Service level agreements not meeting contractual obligations',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Intellectual Property Compliance',
		description: 'Potential IP infringement in product features',
		categoryName: 'Compliance',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Data Localization Requirements',
		description: 'Certain jurisdictions require data to be stored locally',
		categoryName: 'Compliance',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Regulatory Reporting Delays',
		description: 'Delays in submitting required regulatory reports',
		categoryName: 'Compliance',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	// Technology Risks (25 risks)
	{
		name: 'Legacy System Dependencies',
		description: 'Critical functionality depends on outdated legacy systems',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Technical Debt Accumulation',
		description: 'Significant technical debt slowing down development velocity',
		categoryName: 'Technology',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'Cloud Provider Lock-in',
		description: 'Heavy dependency on single cloud provider limiting flexibility',
		categoryName: 'Technology',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'API Versioning Issues',
		description: 'Lack of proper API versioning causing breaking changes',
		categoryName: 'Technology',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Microservices Complexity',
		description: 'Microservices architecture becoming too complex to manage',
		categoryName: 'Technology',
		createdBy: 'system-architect',
		resolved: false,
	},
	{
		name: 'Data Migration Challenges',
		description: 'Complex data migration required with high risk of data loss',
		categoryName: 'Technology',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Incompatible Technology Stack',
		description: 'Current technology stack limiting scalability and performance',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Third-Party API Reliability',
		description: 'Critical third-party APIs experiencing frequent outages',
		categoryName: 'Technology',
		createdBy: 'integration-engineer',
		resolved: false,
	},
	{
		name: 'Mobile Platform Fragmentation',
		description: 'Supporting multiple mobile platforms increasing development complexity',
		categoryName: 'Technology',
		createdBy: 'mobile-developer',
		resolved: false,
	},
	{
		name: 'Browser Compatibility Issues',
		description: 'Application not working properly on older browser versions',
		categoryName: 'Technology',
		createdBy: 'frontend-developer',
		resolved: false,
	},
	{
		name: 'Database Migration Risk',
		description: 'Planned database migration has high risk of downtime',
		categoryName: 'Technology',
		createdBy: 'database-admin',
		resolved: false,
	},
	{
		name: 'Container Orchestration Complexity',
		description: 'Kubernetes setup becoming too complex to maintain',
		categoryName: 'Technology',
		createdBy: 'devops-engineer',
		resolved: true,
	},
	{
		name: 'CI/CD Pipeline Failures',
		description: 'Continuous integration pipeline frequently failing, blocking deployments',
		categoryName: 'Technology',
		createdBy: 'devops-team',
		resolved: false,
	},
	{
		name: 'Code Quality Degradation',
		description: 'Code quality metrics declining over time',
		categoryName: 'Technology',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'Infrastructure Scaling Limitations',
		description: 'Current infrastructure cannot scale to meet demand',
		categoryName: 'Technology',
		createdBy: 'infrastructure-engineer',
		resolved: false,
	},
	{
		name: 'Technology Vendor Dependency',
		description: 'Heavy reliance on single technology vendor',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Data Synchronization Issues',
		description: 'Data synchronization between systems causing inconsistencies',
		categoryName: 'Technology',
		createdBy: 'integration-engineer',
		resolved: false,
	},
	{
		name: 'Performance Bottlenecks',
		description: 'Multiple performance bottlenecks identified in critical paths',
		categoryName: 'Technology',
		createdBy: 'performance-engineer',
		resolved: false,
	},
	{
		name: 'Security Patch Management',
		description: 'Delayed application of security patches increasing vulnerability window',
		categoryName: 'Technology',
		createdBy: 'security-team',
		resolved: false,
	},
	{
		name: 'Technology Skills Gap',
		description: 'Team lacks expertise in required technologies',
		categoryName: 'Technology',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'API Rate Limiting Issues',
		description: 'Third-party APIs rate limiting affecting application functionality',
		categoryName: 'Technology',
		createdBy: 'backend-developer',
		resolved: false,
	},
	{
		name: 'Data Backup System Reliability',
		description: 'Backup systems not tested regularly, reliability unknown',
		categoryName: 'Technology',
		createdBy: 'devops-team',
		resolved: true,
	},
	{
		name: 'Network Infrastructure Outages',
		description: 'Frequent network infrastructure outages affecting service availability',
		categoryName: 'Technology',
		createdBy: 'network-engineer',
		resolved: false,
	},
	{
		name: 'Technology Obsolescence',
		description: 'Key technologies used becoming obsolete',
		categoryName: 'Technology',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Integration Testing Gaps',
		description: 'Insufficient integration testing causing production issues',
		categoryName: 'Technology',
		createdBy: 'qa-engineer',
		resolved: false,
	},
	// Human Resources Risks (25 risks)
	{
		name: 'Key Employee Retention Risk',
		description: 'High risk of losing key technical talent to competitors',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Skills Gap in Development Team',
		description: 'Development team lacks skills in emerging technologies',
		categoryName: 'Human Resources',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'High Employee Turnover',
		description: 'Employee turnover rate above industry average',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Insufficient Training Programs',
		description: 'Lack of ongoing training programs affecting employee growth',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Remote Work Challenges',
		description: 'Managing remote teams creating communication and productivity issues',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Workplace Safety Concerns',
		description: 'Workplace safety issues requiring immediate attention',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Compensation Competitiveness',
		description: 'Compensation packages not competitive with market rates',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Succession Planning Gaps',
		description: 'No succession plan for critical leadership positions',
		categoryName: 'Human Resources',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Employee Burnout Risk',
		description: 'High workload leading to employee burnout',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Diversity and Inclusion Issues',
		description: 'Workplace diversity and inclusion goals not being met',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Recruitment Pipeline Weakness',
		description: 'Insufficient pipeline of qualified candidates for open positions',
		categoryName: 'Human Resources',
		createdBy: 'recruiting-manager',
		resolved: false,
	},
	{
		name: 'Performance Management System',
		description: 'Performance management system not effectively driving results',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: true,
	},
	{
		name: 'Employee Engagement Decline',
		description: 'Employee engagement scores declining over past quarters',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Labor Law Compliance',
		description: 'Potential violations of labor laws in certain jurisdictions',
		categoryName: 'Human Resources',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Contractor Management Issues',
		description: 'Managing large number of contractors creating operational challenges',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Knowledge Management Gaps',
		description: 'Critical knowledge not properly documented, risking loss',
		categoryName: 'Human Resources',
		createdBy: 'engineering-manager',
		resolved: false,
	},
	{
		name: 'Team Collaboration Challenges',
		description: 'Cross-functional teams experiencing collaboration difficulties',
		categoryName: 'Human Resources',
		createdBy: 'project-manager',
		resolved: false,
	},
	{
		name: 'Employee Benefits Costs',
		description: 'Rising employee benefits costs impacting profitability',
		categoryName: 'Human Resources',
		createdBy: 'finance-team',
		resolved: false,
	},
	{
		name: 'Workforce Planning Deficiencies',
		description: 'Inadequate workforce planning for future business needs',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Employee Conflict Resolution',
		description: 'Workplace conflicts not being resolved effectively',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	{
		name: 'Onboarding Process Inefficiencies',
		description: 'New employee onboarding process taking too long',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: true,
	},
	{
		name: 'Talent Acquisition Costs',
		description: 'High costs associated with recruiting and hiring',
		categoryName: 'Human Resources',
		createdBy: 'recruiting-manager',
		resolved: false,
	},
	{
		name: 'Employee Data Privacy',
		description: 'Employee data handling not compliant with privacy regulations',
		categoryName: 'Human Resources',
		createdBy: 'data-protection-officer',
		resolved: false,
	},
	{
		name: 'Organizational Change Resistance',
		description: 'Employee resistance to organizational changes affecting adoption',
		categoryName: 'Human Resources',
		createdBy: 'change-manager',
		resolved: false,
	},
	{
		name: 'Leadership Development Gaps',
		description: 'Insufficient leadership development programs',
		categoryName: 'Human Resources',
		createdBy: 'hr-director',
		resolved: false,
	},
	// Legal Risks (25 risks)
	{
		name: 'Contract Dispute Risk',
		description: 'Ongoing contract dispute with major vendor',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Intellectual Property Infringement',
		description: 'Potential IP infringement claims from competitors',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Litigation Exposure',
		description: 'Potential litigation from customers or partners',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Terms of Service Issues',
		description: 'Terms of service may not adequately protect company interests',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Employment Law Violations',
		description: 'Potential violations of employment laws',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Data Protection Law Compliance',
		description: 'Data protection practices may violate applicable laws',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Regulatory Investigation Risk',
		description: 'Potential regulatory investigation into business practices',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Contractual Obligation Breaches',
		description: 'Risk of breaching contractual obligations with partners',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Trademark Disputes',
		description: 'Trademark disputes affecting brand protection',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Licensing Agreement Violations',
		description: 'Potential violations of software licensing agreements',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'International Law Compliance',
		description: 'Operations in multiple jurisdictions creating legal complexity',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Privacy Policy Compliance',
		description: 'Privacy policy not fully compliant with all applicable laws',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: true,
	},
	{
		name: 'Product Liability Exposure',
		description: 'Product defects creating potential liability exposure',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Antitrust Compliance',
		description: 'Business practices may raise antitrust concerns',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Shareholder Disputes',
		description: 'Potential disputes with shareholders or investors',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Merger and Acquisition Risks',
		description: 'Legal risks associated with M&A activities',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Securities Law Compliance',
		description: 'Potential securities law violations in fundraising',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Export Control Violations',
		description: 'Potential violations of export control regulations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Consumer Protection Lawsuits',
		description: 'Risk of consumer protection lawsuits',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Insurance Coverage Disputes',
		description: 'Disputes with insurance providers over coverage',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Non-Compete Agreement Enforcement',
		description: 'Challenges enforcing non-compete agreements with former employees',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: true,
	},
	{
		name: 'Regulatory Penalty Risk',
		description: 'Risk of regulatory penalties for non-compliance',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Contract Negotiation Delays',
		description: 'Delays in contract negotiations affecting business operations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Intellectual Property Portfolio Gaps',
		description: 'Insufficient IP protection for key innovations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	{
		name: 'Cross-Border Legal Issues',
		description: 'Legal complexities in cross-border operations',
		categoryName: 'Legal',
		createdBy: 'legal-counsel',
		resolved: false,
	},
	// Environmental Risks (15 risks)
	{
		name: 'Carbon Footprint Concerns',
		description: 'High carbon footprint from data center operations',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Energy Consumption',
		description: 'Excessive energy consumption in office and data centers',
		categoryName: 'Environmental',
		createdBy: 'facilities-manager',
		resolved: false,
	},
	{
		name: 'Waste Management Issues',
		description: 'Inadequate waste management and recycling programs',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Water Usage Concerns',
		description: 'High water usage in data center cooling systems',
		categoryName: 'Environmental',
		createdBy: 'facilities-manager',
		resolved: false,
	},
	{
		name: 'E-Waste Disposal',
		description: 'Improper disposal of electronic waste',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Renewable Energy Adoption',
		description: 'Slow adoption of renewable energy sources',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Supply Chain Environmental Impact',
		description: 'Supply chain partners not meeting environmental standards',
		categoryName: 'Environmental',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Climate Change Adaptation',
		description: 'Business operations not adapted to climate change risks',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Environmental Regulatory Compliance',
		description: 'Potential violations of environmental regulations',
		categoryName: 'Environmental',
		createdBy: 'compliance-officer',
		resolved: false,
	},
	{
		name: 'Sustainable Packaging',
		description: 'Product packaging not using sustainable materials',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: true,
	},
	{
		name: 'Biodiversity Impact',
		description: 'Business operations negatively impacting local biodiversity',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Air Quality Concerns',
		description: 'Office air quality not meeting health standards',
		categoryName: 'Environmental',
		createdBy: 'facilities-manager',
		resolved: false,
	},
	{
		name: 'Resource Depletion',
		description: 'High consumption of non-renewable resources',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Environmental Reporting Gaps',
		description: 'Insufficient environmental impact reporting',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	{
		name: 'Greenhouse Gas Emissions',
		description: 'High greenhouse gas emissions from operations',
		categoryName: 'Environmental',
		createdBy: 'sustainability-manager',
		resolved: false,
	},
	// Strategic Risks (15 risks)
	{
		name: 'Market Disruption Risk',
		description: 'Emerging technologies disrupting traditional business model',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Competitive Threat',
		description: 'New competitor entering market with superior technology',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Customer Demand Shift',
		description: 'Changing customer preferences affecting product relevance',
		categoryName: 'Strategic',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Technology Disruption',
		description: 'New technology making current solutions obsolete',
		categoryName: 'Strategic',
		createdBy: 'cto',
		resolved: false,
	},
	{
		name: 'Business Model Viability',
		description: 'Current business model may not be sustainable long-term',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Market Saturation',
		description: 'Target market becoming saturated, limiting growth',
		categoryName: 'Strategic',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Partnership Dependency',
		description: 'Heavy reliance on strategic partnerships creating vulnerability',
		categoryName: 'Strategic',
		createdBy: 'business-development',
		resolved: false,
	},
	{
		name: 'Product-Market Fit Concerns',
		description: 'Product may not have strong product-market fit',
		categoryName: 'Strategic',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Geographic Expansion Risk',
		description: 'Expansion into new markets facing unexpected challenges',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Innovation Pipeline Weakness',
		description: 'Insufficient innovation pipeline to maintain competitive advantage',
		categoryName: 'Strategic',
		createdBy: 'cto',
		resolved: true,
	},
	{
		name: 'Brand Positioning Challenges',
		description: 'Brand positioning not resonating with target audience',
		categoryName: 'Strategic',
		createdBy: 'marketing-director',
		resolved: false,
	},
	{
		name: 'Customer Acquisition Cost',
		description: 'Customer acquisition costs increasing, affecting profitability',
		categoryName: 'Strategic',
		createdBy: 'sales-director',
		resolved: false,
	},
	{
		name: 'Market Entry Barriers',
		description: 'High barriers to entry in target markets',
		categoryName: 'Strategic',
		createdBy: 'business-development',
		resolved: false,
	},
	{
		name: 'Strategic Planning Gaps',
		description: 'Insufficient strategic planning for future growth',
		categoryName: 'Strategic',
		createdBy: 'ceo',
		resolved: false,
	},
	{
		name: 'Competitive Intelligence Gaps',
		description: 'Lack of competitive intelligence affecting strategic decisions',
		categoryName: 'Strategic',
		createdBy: 'business-development',
		resolved: false,
	},
	// Reputational Risks (15 risks)
	{
		name: 'Social Media Backlash',
		description: 'Negative social media sentiment affecting brand reputation',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Customer Satisfaction Decline',
		description: 'Declining customer satisfaction scores',
		categoryName: 'Reputational',
		createdBy: 'customer-success',
		resolved: false,
	},
	{
		name: 'Data Breach Publicity',
		description: 'Public disclosure of data breach affecting customer trust',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Product Quality Issues',
		description: 'Product quality issues being reported publicly',
		categoryName: 'Reputational',
		createdBy: 'product-manager',
		resolved: false,
	},
	{
		name: 'Executive Misconduct Allegations',
		description: 'Allegations of executive misconduct affecting company reputation',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Negative Press Coverage',
		description: 'Sustained negative press coverage affecting brand image',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
	{
		name: 'Customer Review Ratings',
		description: 'Declining customer review ratings on public platforms',
		categoryName: 'Reputational',
		createdBy: 'customer-success',
		resolved: false,
	},
	{
		name: 'Vendor Relationship Issues',
		description: 'Public disputes with vendors affecting reputation',
		categoryName: 'Reputational',
		createdBy: 'procurement-manager',
		resolved: false,
	},
	{
		name: 'Workplace Culture Concerns',
		description: 'Public concerns about workplace culture',
		categoryName: 'Reputational',
		createdBy: 'pr-manager',
		resolved: false,
	},
];

async function seedDatabase() {
	try {
		// Connect to database
		await connectDB();

		// Clear existing data
		console.log('Clearing existing data...');
		await Risk.deleteMany({});
		await Category.deleteMany({});
		console.log('Existing data cleared.');

		// Create categories
		console.log('Creating categories...');
		const createdCategories = await Category.insertMany(categoriesData);
		console.log(`Created ${createdCategories.length} categories.`);

		// Create a map of category names to IDs
		const categoryMap = {};
		createdCategories.forEach((cat) => {
			categoryMap[cat.name] = cat._id;
		});

		// Create risks with category references
		console.log('Creating risks...');
		const risksToInsert = risksData.map((risk) => ({
			name: risk.name,
			description: risk.description,
			categoryId: categoryMap[risk.categoryName],
			createdBy: risk.createdBy,
			resolved: risk.resolved || false,
		}));

		const createdRisks = await Risk.insertMany(risksToInsert);
		console.log(`Created ${createdRisks.length} risks.`);

		// Display summary
		console.log('\n=== Seeding Summary ===');
		console.log(`Categories created: ${createdCategories.length}`);
		console.log(`Risks created: ${createdRisks.length}`);
		console.log(`\nRisks by category:`);
		const risksByCategory = createdRisks.reduce((acc, risk) => {
			const key = risk.categoryId.toString();
			acc[key] = (acc[key] || 0) + 1;
			return acc;
		}, {});

		createdCategories.forEach((cat) => {
			const count = risksByCategory[cat._id.toString()] || 0;
			console.log(`  ${cat.name}: ${count}`);
		});

		const resolvedCount = createdRisks.filter((r) => r.resolved).length;
		console.log(`\nResolved risks: ${resolvedCount}`);
		console.log(`Unresolved risks: ${createdRisks.length - resolvedCount}`);

		console.log('\n✅ Database seeded successfully!');
		process.exit(0);
	} catch (error) {
		console.error('❌ Error seeding database:', error);
		process.exit(1);
	}
}

seedDatabase();
